name: Python CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python 3.12
        run: uv python install 3.12

      - name: Sync dependencies
        run: uv sync

      - name: Ruff
        run: uv run ruff check .

      - name: Black
        run: uv run black --check .

      - name: Pytest
        run: uv run pytest